### ISSUE TITLE
论文请问现在可见了嘛，好像已经中了

### ISSUE THREAD

**Issue by hackerchenzhuo** [nju-websoft/RoadEA#3]

**Comment by sunzequn** [comment]
同学你好，感谢你对我们工作的关注。论文我已经提交给期刊了，应该会很快online，到时候我再告知你。

**Comment by hackerchenzhuo** [comment]
噢噢请问你们会考虑挂arxiv或者上传pdf至github嘛？

**Comment by sunzequn** [comment]
同学你好，考虑潜在版权问题，暂时没有挂到arxiv的打算。感谢你的关注！
